version: '3.8'

services:
  api:
    build: .
    container_name: datathon_api
    ports:
      - "8000:8000"
    volumes:
      - ./build:/app/build
      - ./mlflow.db:/app/mlflow.db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - prometheus

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow_server
    ports:
      - "5000:5000"
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db
    volumes:
      - ./mlflow.db:/mlflow.db
      - ./mlruns:/mlruns

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus